name: Build and Push Docker Image

on:
  push:
    branches:
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Build Docker image with date and time tag
    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        TAG="nsaepitechrennes/sample-app-app:$(date +'%Y%m%d%H%M')"
        echo "Tagging image with tag: $TAG"
        docker build -t $TAG .
        docker tag $TAG $TAG

    # Login to Docker Hub and Push Docker image
    - name: Login to Docker Hub and Push Docker image
      run: |
        echo "Logging into Docker Hub..."
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Pushing Docker image..."
        docker push $TAG  # Utilisation correcte de la variable TAG
