name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Changer en votre branche principale si nécessaire
  pull_request:
    branches: 
      -  main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Ajoutez ici les étapes pour la construction de votre image Docker
    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t nsaepitechrennes/yourimage:latest .

    # Ajoutez ici les étapes pour le login à Docker Hub et le poussage de l'image
    - name: Login to Docker Hub and Push Docker image
      run: |
        echo "Logging into Docker Hub..."
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Pushing Docker image..."
        docker push nsaepitechrennes/nsa-800:latest
