#name: Build and Push Docker Image

#on:
#  push:
#    branches:
#      - main  # Changer en votre branche principale si nécessaire
#  pull_request:
#    branches: 
#      -  main

#jobs:
#  build:
#    runs-on: ubuntu-latest

#    steps:
#    - name: Checkout repository
#      uses: actions/checkout@v3

    # Ajoutez ici les étapes pour la construction de votre image Docker