name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # Changer en votre branche principale si nécessaire
  pull_request:
    branches: 
      -  main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    # Ajoutez ici les étapes pour la construction de votre image Docker
    - name: Build Docker image
      run: |
        echo "Building Docker image..."
        docker build -t nsaepitechrennes/sample-app-app:${GITHUB_RUN_NUMBER} .

    # Ajoutez ici les étapes pour le login à Docker Hub et le poussage de l'image
    - name: Login to Docker Hub and Push Docker image
      run: |
        echo "Logging into Docker Hub..."
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        echo "Pushing Docker image..."
        docker push nsaepitechrennes/sample-app-app:${GITHUB_RUN_NUMBER}
   
  deploy:
    name: Deploy to server
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH into server and deploy
        env:
          DOCKER_TAG: ${GITHUB_RUN_NUMBER}
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: 22
          username: admuser
          key: ${{ secrets.SERVER_HOST_SSH }}
          passphrase: ${{ secrets.SERVER_HOST_SSH_PASSPHRASE }}
          envs: DOCKER_TAG
          script: |
            docker pull nsaepitechrennes/sample-app-app:$DOCKER_TAG
            docker stop LostOps
            docker rm LostOps
            docker run -d --name LostOps -p 81:80 nsaepitechrennes/sample-app-app:$DOCKER_TAG
